services:
  postgres-test:
    image: postgres:16
    container_name: postgres-db-test
    environment:
      POSTGRES_DB: gametime_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
        - custom-net
volumes:
  pgdata_test:
networks:
  custom-net:
    name: game-time-net