services:
  postgres-prod:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: gametime
      POSTGRES_USER: gametime_user
      POSTGRES_PASSWORD: gametime_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        - custom-net
volumes:
  pgdata:

networks:
  custom-net:
    name: game-time-net
